version: 2
updates:
  - package-ecosystem: "maven"
    directory: /
    schedule:
      interval: "daily"
    assignees:
      - "Andras-Csanyi"
    commit-message:
      prefix: "fix(dependency upgrades)"
    groups:
      library-upgrades:
        patterns:
          - "*"
